import{a as S,S as v,i as c}from"./assets/vendor-5YrzWRhu.js";(function(){const a=document.createElement("link").relList;if(a&&a.supports&&a.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&o(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function o(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();const q="51769269-403519ddb75627d5d460176b7",M="https://pixabay.com/api/",$=15;async function m(r,a=1){try{return(await S.get(M,{params:{key:q,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:a,per_page:$}})).data}catch(s){throw console.error("Error fetching images:",s),new Error("Failed to fetch images from Pixabay API")}}const p=document.querySelector(".gallery"),f=document.querySelector(".loader"),g=document.querySelector(".btn"),B=new v(".gallery a",{captionsData:"alt",captionDelay:250});function y(r){const a=r.map(({webformatURL:s,largeImageURL:o,tags:e,likes:t,views:n,comments:E,downloads:P})=>`
      <li class="gallery-item">
        <a href="${o}">
          <img src="${s}" alt="${e}" loading="lazy"/>
        </a>
        <div class="info">
           <p><b>Likes:</b> ${t}</p>
          <p><b>Views:</b> ${n}</p>
          <p><b>Comments:</b> ${E}</p>
          <p><b>Downloads:</b> ${P}</p>
        </div>
      </li>
    `).join("");p.insertAdjacentHTML("beforeend",a),B.refresh()}function R(){p.innerHTML=""}function h(){f.classList.remove("hidden")}function b(){f.classList.add("hidden")}function x(){g.classList.remove("hidden")}function L(){g.classList.add("hidden")}const A=document.querySelector(".form"),u=document.querySelector(".btn");let l="",i=1,d=0;const w=15;A.addEventListener("submit",async r=>{var s;if(r.preventDefault(),l=document.querySelector('input[name="search-text"]').value.trim(),!l){c.error({title:"Error",message:"Please enter a search query",position:"topRight"});return}i=1,h(),L(),(s=document.querySelector(".end-message"))==null||s.remove();try{const o=await m(l,i);if(d=o.totalHits,R(),o.hits.length===0){c.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again.",position:"topRight"});return}y(o.hits),c.success({title:"Success",message:`Hooray! We found ${d} images.`,position:"topRight"}),i*w<d?x():showEndMessage()}catch(o){console.error("Error:",o),c.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}finally{b()}});u.addEventListener("click",async()=>{i+=1,h(),u.disabled=!0;try{const r=await m(l,i);y(r.hits),window.scrollBy({top:600,behavior:"smooth"}),i*w>=d&&(L(),showEndMessage())}catch(r){console.error("Error:",r),c.error({title:"Error",message:"Failed to load more images. Please try again.",position:"topRight"})}finally{b(),u.disabled=!1}});
//# sourceMappingURL=index.js.map
