import{a as v,S as q,i as c}from"./assets/vendor-5YrzWRhu.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&o(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const M="51769269-403519ddb75627d5d460176b7",$="https://pixabay.com/api/",x=15;async function m(t,n=1){try{return(await v.get($,{params:{key:M,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:n,per_page:x}})).data}catch(s){throw console.error("Error fetching images:",s),new Error("Failed to fetch images from Pixabay API")}}const p=document.querySelector(".gallery"),f=document.querySelector(".loader"),y=document.querySelector(".btn"),B=new q(".gallery a",{captionsData:"alt",captionDelay:250});function g(t){const n=t.map(({webformatURL:s,largeImageURL:o,tags:e,likes:r,views:i,comments:P,downloads:S})=>`
      <li class="gallery-item">
        <a href="${o}">
          <img src="${s}" alt="${e}" loading="lazy"/>
        </a>
        <div class="info">
           <p><b>Likes:</b> ${r}</p>
          <p><b>Views:</b> ${i}</p>
          <p><b>Comments:</b> ${P}</p>
          <p><b>Downloads:</b> ${S}</p>
        </div>
      </li>
    `).join("");p.insertAdjacentHTML("beforeend",n),B.refresh()}function R(){p.innerHTML=""}function h(){f.classList.remove("hidden")}function b(){f.classList.add("hidden")}function A(){y.classList.remove("hidden")}function L(){y.classList.add("hidden")}function E(){const t=document.createElement("p");t.classList.add("end-message"),t.textContent="We're sorry, but you've reached the end of search results.",document.querySelector(".btn-container").after(t)}const O=document.querySelector(".form"),u=document.querySelector(".btn");let l="",a=1,d=0;const w=15;O.addEventListener("submit",async t=>{var s;if(t.preventDefault(),l=document.querySelector('input[name="search-text"]').value.trim(),!l){c.error({title:"Error",message:"Please enter a search query",position:"topRight"});return}a=1,h(),L(),(s=document.querySelector(".end-message"))==null||s.remove();try{const o=await m(l,a);if(d=o.totalHits,R(),o.hits.length===0){c.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again.",position:"topRight"});return}g(o.hits),c.success({title:"Success",message:`Hooray! We found ${d} images.`,position:"topRight"}),a*w<d?A():E()}catch(o){console.error("Error:",o),c.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}finally{b()}});u.addEventListener("click",async()=>{a+=1,h(),u.disabled=!0;try{const t=await m(l,a);g(t.hits),window.scrollBy({top:600,behavior:"smooth"}),a*w>=d&&(L(),E())}catch(t){console.error("Error:",t),c.error({title:"Error",message:" Failed to load more images. Please try again.",position:"topRight"})}finally{b(),u.disabled=!1}});
//# sourceMappingURL=index.js.map
