import{a as M,S as B,i as a}from"./assets/vendor-LK6CqzKq.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))c(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const d of o.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&c(d)}).observe(document,{childList:!0,subtree:!0});function i(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function c(t){if(t.ep)return;t.ep=!0;const o=i(t);fetch(t.href,o)}})();const P="51769269-403519ddb75627d5d460176b7",S="https://pixabay.com/api/",v=15;async function p(r,e){return(await M.get(S,{params:{key:P,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:v}})).data}const R=document.querySelector(".gallery"),m=document.querySelector(".loader"),g=document.querySelector(".btn"),h=new B(".gallery a",{captionsData:"alt",captionDelay:250});function y(r){return r.map(({webformatURL:e,largeImageURL:i,tags:c,likes:t,views:o,comments:d,downloads:w})=>`
      <li class="gallery-item">
        <a href="${i}">
          <img src="${e}" alt="${c}" loading="lazy"/>
        </a>
        <div class="info">
           <p><b>Likes:</b> ${t}</p>
          <p><b>Views:</b> ${o}</p>
          <p><b>Comments:</b> ${d}</p>
          <p><b>Downloads:</b> ${w}</p>
        </div>
      </li>
    `).join("")}function q(){R.innerHTML=""}function b(){m.classList.remove("hidden")}function u(){m.classList.add("hidden")}function $(){g.classList.remove("hidden")}function x(){g.classList.add("hidden")}const n={formEl:document.querySelector(".form"),ulElem:document.querySelector(".gallery"),loaderMoreBtn:document.querySelector(".btn")};let f="",l,s=0,I=15;n.formEl.addEventListener("submit",async r=>{if(r.preventDefault(),l=1,b(),f=r.target.elements["search-text"].value.trim(),!f){a.error({title:"Error",message:"Please fill in the field",position:"topRight",color:"red"}),u();return}q();try{const e=await p(f,l);if(e.hits.length===0){a.info({title:"Info",message:"Nothing found for your query.",position:"topRight"}),u();return}const i=y(e.hits);n.ulElem.innerHTML=i,s=Math.ceil(e.totalHits/I),h.refresh(),r.target.reset()}catch(e){console.error(e),s=0,a.error({title:"Error",message:"Something went wrong!",position:"topRight",color:"red"})}finally{u()}L(),E()});n.loaderMoreBtn.addEventListener("click",async()=>{var r;l+=1,n.loaderMoreBtn.disabled=!0,b();try{const e=await p(f,l);if(e.hits.length===0){E(),n.loaderMoreBtn.style.display="none";return}const i=y(e.hits);n.ulElem.insertAdjacentHTML("beforeend",i);const c=((r=n.ulElem.firstElementChild)==null?void 0:r.getBoundingClientRect().height)||300;window.scrollBy({top:c*2,behavior:"smooth"}),h.refresh(),L()}catch(e){console.error("Error loading more images:",e),a.error({title:"Error",message:"Failed to load more images",position:"topRight",color:"red"})}finally{u(),n.loaderMoreBtn.disabled=!1}});function L(){l<s?$():x()}function E(){l===1&&s!==0?a.info({title:"Info",message:`MaxPage - ${s}`,position:"topRight"}):s===0?a.info({title:"Info",message:"Nothing found",position:"topRight"}):l===s&&a.info({title:"Info",message:"This is the last page",position:"topRight"})}
//# sourceMappingURL=index.js.map
